baseURL = 'https://icstudio.club/'
languageCode = 'en-us'
title = 'IC Studio'

[[menus.main]]
name = '主页'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Blog'
pageRef = 'blog'
weight = 12

[[menus.main]]
name = '视奏工具'
url = 'https://icstudio.club/tools/sight-reading-generator.html'
weight = 20

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      
[params]
  logo = "images/ICLOGO.png"
  favicon_icon = "ICLOGO.png"
  description = "欢迎来到 IC Studio 官方网站！一个分享音乐学习过程与经验的平台。"
  mainSections = ["blog", "视奏工具"]

[pagination]
  pagerSize = 6

[taxonomies]
  category = "categories"
  tag = "tags"

[outputs]
  home = ["HTML", "RSS", "JSON"]